# Generated by Django 3.2.25 on 2024-03-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripttion',
            new_name='description',
        ),
    ]
